chore: porting the tutorial from branch proposal_v2.0 to main
autowarefoundation/open-ad-kit-docs pull request #31
Opened 2022-09-23 03:49 UTC by evshary

The Version 2.0 tutorial on the documentation website is still the same as Version 1.0.
I've followed the tutorial in the proposal_v2.0 branch and it works well, so I think it'll be great if we can put it on the website.
Every new developer who is interested in the Open AD Kit can try the latest version.
If there are any issues with the tutorial, we can also correct them fast.

I didn't join the discussion of the website before, so if there are any concerns about this, please let me know.

2022-09-28 09:05 UTC, d-hashimoto commented
@evshary Thank you for your dedication! If you can add label "documentation" to this PR, the GitHub page will be created for your PR.

@ito-san I would appreciate it if you could review this PR. This PR seems to be derived from [your proposal branch](https://github.com/autowarefoundation/open-ad-kit-docs/tree/proposal_v2.0/docs).

2022-09-28 09:31 UTC, evshary commented
> @evshary Thank you for your dedication! If you can add label "documentation" to this PR, the GitHub page will be created for your PR.
> 
> @ito-san I would appreciate it if you could review this PR. This PR seems to be derived from [your proposal branch](https://github.com/autowarefoundation/open-ad-kit-docs/tree/proposal_v2.0/docs).

@d-hashimoto Thanks for your reply. It seems like I don't have the privilege to add label. I'll ask for help.

2022-09-29 02:59 UTC, evshary commented
I'm just aware that most of the commits in proposal_v2.0 are contributed by @ito-san.
Therefore I've updated the author in the git commit for giving the correct credit.
If you prefer to merge proposal_v2.0 to the main branch directly, please let me know. I can close this PR.
It's really convenient to have OADK 2.0 on the website, and I'm happy to make it happen sooner.

2022-09-29 06:17 UTC, ito-san commented
@evshary Amazing, This is a great PR made by you! :clap:

2022-09-29 06:22 UTC, ito-san requested changes

2022-09-29 06:22 UTC, ito-san commented on docs/version-2.0/start-guide/installation/advanced-setup-setup-ava.md
> +   wget -P ~/meta-adlink-ampere/meta-ewaol-ext/recipes-ewaol/recipes-container/nvidia-container-toolkit/files https://raw.githubusercontent.com/autowarefoundation/open-ad-kit-docs/proposal_v2.0/docs/
Please do not use `proposal_v2.0` and correct the path to the file.

2022-09-29 06:22 UTC, ito-san commented on docs/version-2.0/start-guide/installation/system-setup-ava.md
> +   wget https://raw.githubusercontent.com/autowarefoundation/open-ad-kit-docs/proposal_v2.0/docs/start-guide/installation/deployments/comhpc-deployments.zip
Please do not use `proposal_v2.0` and correct the path to the file.

2022-09-29 06:22 UTC, ito-san commented on docs/version-2.0/start-guide/installation/system-setup-ava.md
> +   wget -P /etc/sysctl.d https://raw.githubusercontent.com/autowarefoundation/open-ad-kit-docs/proposal_v2.0/docs/start-guide/installation/sysctl.d/60_cyclonedds.conf
Please do not use `proposal_v2.0` and correct the path to the file.

2022-09-29 06:22 UTC, ito-san commented on docs/version-2.0/start-guide/installation/system-setup-ava.md
> +   wget -P ~/cyclonedds https://raw.githubusercontent.com/autowarefoundation/open-ad-kit-docs/proposal_v2.0/docs/start-guide/installation/cyclonedds/cyclonedds.xml
Please do not use `proposal_v2.0` and correct the path to the file.

2022-09-29 06:22 UTC, ito-san commented on docs/version-2.0/start-guide/installation/system-setup-host.md
> +   wget -P /etc/sysctl.d https://raw.githubusercontent.com/autowarefoundation/open-ad-kit-docs/proposal_v2.0/docs/start-guide/installation/sysctl.d/60_cyclonedds.conf
Please do not use `proposal_v2.0` and correct the path to the file.

2022-09-29 06:22 UTC, ito-san commented on docs/version-2.0/start-guide/installation/system-setup-host.md
> +   wget -P ~/cyclonedds https://raw.githubusercontent.com/autowarefoundation/open-ad-kit-docs/proposal_v2.0/docs/start-guide/installation/cyclonedds/cyclonedds.xml
Please do not use `proposal_v2.0` and correct the path to the file.

2022-09-29 07:50 UTC, evshary commented
@ito-san Thank you! I've already fixed the links.

2022-09-29 08:20 UTC, ito-san approved these changes
@evshary Thank you for the fix! LGTM.

2022-09-29 22:21 UTC, merged